on:
  push:
    branches:
      - "*"
      - "**/*"
      - "!master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "This branch will be deployed to [dev.cultureamp.design/${{ github.ref }}](https://dev.cultureamp.design/${{ github.ref }})"
